//
// Created by fr0sty on 25/06/2023.
//

#ifndef FR0STY_ENGINE_FRAMEWORK_COMPONENTS_H
#define FR0STY_ENGINE_FRAMEWORK_COMPONENTS_H

#include "framework_button.h"

#endif //FR0STY_ENGINE_FRAMEWORK_COMPONENTS_H
